version: "3.1"

services:
  mariadb:
    image: mariadb:11.0.1-rc-jammy
    container_name: cinema_api_mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - ${PWD}/mariadb/:/var/lib/mysql
      - ./db_script/:/docker-entrypoint-initdb.d:ro
    ports:
      - 3306:3306

  adminer:
    image: iutsd/adminer
    container_name: cinema_api_adminer
    build:
      context: ./adminer
    ports:
      - 8001:80
